using Content.Client.Administration.Managers;
using Robust.Client.AutoGenerated;
using Robust.Client.Mapping;
using Robust.Client.Mapping.UserInterface;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.Tabs.AdminbusTab
{
    [GenerateTypedNameReferences]
    public partial class AdminbusTab : Control
    {
        private EntitySpawnWindow? _entitySpawnWindow;
        private TileSpawnWindow? _tileSpawnWindow;

        protected override void EnteredTree()
        {
            // For the SpawnEntitiesButton and SpawnTilesButton we need to do the press manually
            // TODO: This will probably need some command check at some point
            SpawnEntitiesButton.OnPressed += SpawnEntitiesButtonOnOnPressed;
            SpawnTilesButton.OnPressed += SpawnTilesButtonOnOnPressed;
        }

        private void SpawnEntitiesButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
        {
            _entitySpawnWindow ??= new EntitySpawnWindow(
                EntitySystem.Get<MappingSystem>(),
                EntitySystem.Get<PlacementSystem>(),
                IoCManager.Resolve<IPrototypeManager>(),
                IoCManager.Resolve<IResourceCache>(),
                IoCManager.Resolve<IPlacementManager>());
            EntitySystem.Get<AdminSystem>().OpenCommand(_entitySpawnWindow);
        }

        private void SpawnTilesButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
        {
            _tileSpawnWindow ??= new TileSpawnWindow(IoCManager.Resolve<ITileDefinitionManager>(),
                EntitySystem.Get<MappingSystem>(),
                IoCManager.Resolve<IResourceCache>());
            EntitySystem.Get<AdminSystem>().OpenCommand(_tileSpawnWindow);
        }
    }
}
